### ISSUE TITLE
 productFlavors  的问题

### ISSUE THREAD

**Issue by KeqingLI** [TinkerPatch/tinkerpatch-andresguard-sample#1]
productFlavors {
        flavor1 {
            applicationId 'com.tinkerpatch.easy_sample.flavor1'
        }
        flavor2 {
            applicationId 'com.tinkerpatch.easy_sample.flavor2'
        }
}
多渠道打包的方式 不能在baseApk文件夹下生成混淆资源的包 请问需要修改哪个路径

**Comment by simpleton** [comment]
这个是多flavor的sample,https://github.com/TinkerPatch/tinkerpatch-flavors-sample
如果是要结合多flavor和AndResGuard，可能需要修改一下`andresguard.gradle`文件。

**Comment by KeqingLI** [comment]
额 我知道是andresguard.gradle的某个路径问题 不过对gradle不太熟 我还是以后研究一下了再考虑多渠道吧
